### ISSUE TITLE
Package structure and imports

### ISSUE THREAD

**Issue by RossBoylan** [ucsf-deb/bifs#19]
Motivating Issue
===========
`
import bifs `
does not throw an error, but also doesn't seem to import anything, when invoked from a program in the examples directory.  I was running it from the top directory of this project, and suspect that means it attempted to import from the bifs subdirectory.  That subdirectory has an `__init__.py`, a requirement for modules, but that file has no executable code.

I suspect the fact that bifs_gui runs from the src directory and executes `import bifs` is misleading.  The import is getting only the bifs.py file (according to the metadata), not the whole package.

Attempted Solutions
=============
Added `from .src import *` to the `__init__.py` file.
When that didn't work, created an `__init__.py` in the src directory.
When that didn't work, put `from .bifs import bifs` in the latter `__init__.py`
With those changes my test program was able to import bifs and execute
`bifs.bifs()`.

However, that method failed because it tries to
`import bases.fourier as fb`
and can't find anything.
Changing it to 
`from .bases import fourier as fb`
allows success.

But this change renders bifs_gui non-functional, at least when run in place, because when it triggers the same code it complains that there is no top-level module.  The fact that the code in bifs.py did not think it was in a module, even though it was there because bifs_gui imported it, supports the earlier theory that the current `import bifs` is not doing a regular module import.

General Issues
=========

1. Why do we have a src directory?
2. Generally, should python modules be runnable from the source tree, or do they require an installation process?
3. What is a proper module structure?
    a.  Should there be an `__init__.py` in each directory?
    b.  What should the `__init__.py` do?  Other examples I've seen define things like version and author; the docs say that if `__all__` is defined it gives the public symbols (if omitted, every symbol not starting with `_` is public).  And generally they do imports to pull in code.
    c. Should the public exports be defined in the top level `__init__.py`, or 
       cumulated up from the levels nearest to the code that defines them?
4. What's the best way for components to refer to each other?  By "best" I mean most likely to be indifferent to the current working directory, to whether we are in the source tree or installed, and to whether we are in a module context or not?
5. bifs_gui.py seems unlike some of the other modules.  The code mostly defines a library of functions and classes that could be used in other programs.  But bifs_gui is a free-standing application that uses the rest of the library.  What are the packaging implications of those facts?  There may be other code that is intended an application (not necessarily graphical)--I'm thinking of the bifs_util directory as well the examples directory.

**Comment by RossBoylan** [comment]
My reading of the Python documentation on modules is that the answer to **3a** is Yes.
If a.b.c is a module then a and b must have an `__init__.py`, as must c if it is a directory (it could be an individual .py file or, in some contexts, a symbol defined in a.b).

Also the general consensus on **point 1** seems to be there is no good reason to have a `src` directory.

**Point 4**: generally components should refer to each other using relative paths (leading dots).  I think `.` is defined as the directory the file with the code is in.  However, this is not appropriate for free standing programs, which I think includes `bifs_gui` (**point 5**).  It should be able to `import bifs` to get the rest of the package, but it should not use relative references itself, since it may be run from anywhere and is likely executing in a script, not module, context.

It appears the convention is that it is the responsibility of the user/test environment/package installer to assure that `import bifs` can find the proper directory.  Note that this command means something radically different when executed from the directory in which `bifs.py` exists, as is currently the case when `bifs_gui` is run in place, from what it means when invoked elsewhere.  In the former case it is close to an include directive for `bifs.py`.  From most other places it would attempt to import the entire module.  As noted, the latter scenario doesn't work for now.

**Comment by RossBoylan** [comment]
src directory
========

Despite our previous consensus that the `src` directory was pointless, the documents for `pytest` refer favorably to https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure, an argument for using a `src` directory.  Note:

1. They recommend `src/bifs`, not the `bifs/src` that we are currently using.
2. The recommendation is partly based on the fact that it makes some things harder to do, namely testing the code without installing it.  I'm not sure we want to make it harder.
3. This directory structure is only 1 of 2 methods pytest suggests at https://docs.pytest.org/en/latest/goodpractices.html#goodpractices.  However, the alternative would make the tests part of the distributable package.  Although that has something to recommend it, and is standard for `R`, it has the obvious drawback of including a lot of stuff, including test images, that most people won't need.

**Comment by dtribose** [comment]
I think we can eliminate the src directory altogether. i.e. do not use src/bifs or bifs/src: Just use bifs. Here are a few references that suggest this:
https://docs.python-guide.org/writing/structure/
https://uoftcoders.github.io/studyGroup/lessons/python/packages/lesson/
Also, as I mentioned in an email, the GitHub sites for numpy, xarray, the python requests library, as well as nose use this structure.
https://github.com/numpy/numpy
https://github.com/pydata/xarray
https://github.com/psf/requests
https://github.com/nose-devs/nose
PyTest suggest using src/bifs style in the case where the naming of test files cannot be made unique, which I don't think is a problem for most projects. Also, it lists some benefits of using just the project name with no 'src' directory, in the section "Tests outside application code". It indicates this allows testing after installing remotely via pip, or after locally using pip install --editable (for locally testing a pip install), or if you want to just test in your source repository. This may make your imports and testing easier.
Also I'm a little suspicious of that blog post, since it was written in 2014, and the python-guide.org is up to date as of 2019.
@RossBoylan, @kyoung21b

**Comment by RossBoylan** [comment]
Your latest commit 4ea86cf50bdd5c81936faf5da9ca506379f38c93 seems to have recreated the src directory.  The comment says it’s “for packaging.”  Could you expand a bit about your current thinking on this issue?

I’m trying to integrate the various strands of work.
Ross

**Comment by dtribose** [comment]
Hi Ross,
Glad to hear you are looking at this.I got super busy with my job search and now working full time with a GenapSys in Redwood City, so I do a lot of traveling.

The last comment was mainly to indicate that the successful package creation on the test-PyPI system could be created with (or without) the code in a src subdirectory. I did this in part because I saw more instances where having a src subdirectory was gaining popularity with some popular speakers due to it's support for a certain testing library.

I'm staying over at a hotel in R.C. tonight, but I could dig more into my notes and review my changes in a bit more detail tomorrow night, if that is desired.
Hope this helps.Cheers, David

    On Monday, January 27, 2020, 12:03:43 PM PST, RossBoylan <notifications@github.com> wrote:  
 
 Your latest commit 4ea86cf50bdd5c81936faf5da9ca506379f38c93 seems to have recreated the src directory. The comment says it’s “for packaging.” Could you expand a bit about your current thinking on this issue?

I’m trying to integrate the various strands of work.
Ross

**Comment by RossBoylan** [comment]
The original problem stemmed from the fact that `import bifs` could either mean import the whole package or import the `bifs.py` file, depending on the environment one was running in.  The solution was to rename bifs.py to `bifscore.py`.
Fixed by 91a4d96ecce122d5c506ff19186768bf83cac6ab
